site_name: BMCDocs
site_description: Documentation for vendor BMC tools like Dell RACADM, Supermicro SUM/SAA, etc.
site_author: Jesse Butryn

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# nav:
#   - Home: index.md
#   - 'Dell :fontawesome-solid-server:':
#     - 'RACADM :material-console:':
#       - Overview: dell/racadm/index.md
#       - 'Get Command :material-download:': dell/racadm/get.md
#       - 'Set Command :material-upload:': dell/racadm/set.md
#       - 'Subcommands :material-menu:': dell/racadm/subcommands/
#   - 'Supermicro :fontawesome-solid-microchip:':
#     - 'SUM :material-package-variant:': supermicro/sum/
#     - 'SAA :material-shield-check:': supermicro/saa.md

plugins:
  - search
  - awesome-pages

extra_css:
  - stylesheets/extra.css
